Repository cslant/laravel-telegram-git-notifier, pull requests merged in 2024-02, with the labels that each got.

#62 create star action template
  lang/de/events/github/star.php
  lang/de/events/github/watch.php
  lang/en/events/github/star.php
  lang/en/events/github/watch.php
  lang/ja/events/github/star.php
  lang/ja/events/github/watch.php
  lang/vi/events/github/star.php
  lang/vi/events/github/watch.php
  resources/views/events/github/meta/deleted.blade.php
  resources/views/events/github/star/created.blade.php
  resources/views/events/github/star/deleted.blade.php
Labels: enhancement

#63 Fix blade & translations
  lang/de/events/github/branch_protection_rule.php
  lang/de/events/github/issues.php
  lang/de/events/github/star.php
  lang/de/events/github/watch.php
  lang/de/events/github/workflow_job.php
  lang/de/events/github/workflow_run.php
  lang/en/events/github/branch_protection_rule.php
  lang/en/events/github/issues.php
  lang/en/events/github/star.php
  lang/en/events/github/watch.php
  lang/en/events/github/workflow_job.php
  lang/en/events/github/workflow_run.php
  lang/ja/events/github/branch_protection_rule.php
  lang/ja/events/github/issues.php
  lang/ja/events/github/star.php
  lang/ja/events/github/watch.php
  lang/ja/events/github/workflow_job.php
  lang/ja/events/github/workflow_run.php
  lang/vi/events/github/branch_protection_rule.php
  lang/vi/events/github/issues.php
  lang/vi/events/github/star.php
  lang/vi/events/github/workflow_job.php
  lang/vi/events/github/workflow_run.php
  resources/views/events/github/branch_protection_rule/created.blade.php
  resources/views/events/github/branch_protection_rule/deleted.blade.php
  resources/views/events/github/branch_protection_rule/edited.blade.php
  resources/views/events/github/star/created.blade.php
  resources/views/events/github/star/deleted.blade.php
  resources/views/events/github/watch/started.blade.php
  resources/views/events/github/workflow_job/completed.blade.php
  resources/views/events/github/workflow_job/in_progress.blade.php
  resources/views/events/github/workflow_job/queued.blade.php
  resources/views/events/github/workflow_run/completed.blade.php
  resources/views/events/github/workflow_run/requested.blade.php
Labels: bug

#60 Update documentations and commands
  README.md
  composer.json
  resources/views/tools/custom_event.blade.php
  src/Commands/ChangeOwnerConfigJson.php
Labels: documentation, enhancement
